### PR TITLE
use YAML.unsafe_load if available

### LINKED ISSUE #10: Breaks with modern Ruby
openuri-cached breaks with 

```
lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: URI::HTTPS (Psych::DisallowedClass)
	from /Volumes/nar/Users/cabo-rescue/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'

```

in cached.rb:39:

```
        meta = YAML::load(File.read("#{filename}.meta")) if File.exists?("#{filename}.meta")
```

The problem is this entry in the metadata:

```
:base_uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
```

This is storing the URI object, which doesn't seem to survive YAML and back any more.

I'd store the URI string instead, and convert back upon reading.

### PR DESCRIPTION
**Pull request by mojavelinux**
fixes compatibility with Ruby 3.1

resolves #10

### CODE REVIEW

**Comment by mojavelinux** [comment]
If you'd like, I could resolve the method first, then use `.call` to invoke it.

**Comment by tigris** [comment]
Is this dependant on what `yaml` parser you're using? I just tested on ruby `3.0.2` and `YAML.load` seemed to marshal/unmarshal the meta content just fine. Hmm.

**Comment by mojavelinux** [comment]
Ruby 3.0 is not the issue. The issue is Ruby 3.1.

**Comment by mojavelinux** [comment]
Here's a demonstration of the problem: https://github.com/mojavelinux/open-uri-cached/runs/4648814824?check_suite_focus=true

**Comment by tigris** [comment]
> Ruby 3.0 is not the issue. The issue is Ruby 3.1.

That makes sense. I haven't toyed with `3.1` locally yet. It was only released 2 days ago after all 🤣

**Comment by mojavelinux** [comment]
>  It was only released 2 days ago after all

Yep, I know it's extremely fresh. But if I don't update immediately, I get flooded with issues and requests if it breaks something. So I've learned to get ahead of the game ;) And GitHub Actions makes doing that simpler than ever before.

**Pull request merged**
